export class AchievementData {
  constructor(
    public name: string = '',
    public description: string = '',
    public points: string = '',
    public pack: string = '',
    public category: string = '',
    public enabled: boolean = true
  ) {}
}

export const ACHIEVEMENTS: AchievementData[] = [
  {
    name: 'Are You Entertained?',
    description: 'Have a Sim reach max level in the Entertainer career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Captain of Industry',
    description: 'Have a Sim reach the max level in the Business career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Clued In',
    description: 'Have a Sim reach max level in the Detective career',
    points: '50',
    pack: 'Get To Work',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Down To A Science',
    description: 'Have a Sim reach max level in the Scientist career',
    points: '50',
    pack: 'Get To Work',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Flying Colors',
    description: 'Have a Sim reach max level in the Painter career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'I, Spy',
    description: 'Have a Sim reach max level in the Secret Agent career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Patients Are A Virtue',
    description: 'Have a Sim reach max level in the Doctor career',
    points: '50',
    pack: 'Get To Work',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Startup Upstart',
    description: 'Have a Sim reach max level in the Tech Guru career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Stellar Work',
    description: 'Have a Sim reach max level in the Astronaut career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Suave Criminal',
    description: 'Have a Sim reach max level in the Criminal career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'The Pen is Mightier',
    description: 'Have a Sim reach max level in the Writer career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Up a Notch',
    description: 'Have a Sim reach max level in the Culinary Career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'World Competitor',
    description: 'Have a Sim reach max level in the Athletic career.',
    points: '50',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Knack of All Trades',
    description: 'Reach max level in every career in The Sims 4.',
    points: '100',
    pack: 'Base Game',
    category: 'Career',
    enabled: true,
  },
  {
    name: 'Polar Bear Club',
    description: 'Have a Sim go for a swim while the weather is freezing.',
    points: '25',
    pack: 'Seasons',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: "View All Myshuno Meadows' Sculptures",
    description: "View all of Myshuno Meadows' sculpture descriptions",
    points: '25',
    pack: 'City Living',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'No Excuse',
    description: 'Have a Sim’s bladder fail on a lot with 5 or more toilets.',
    points: '10',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'So… I’ll call you?',
    description: 'Have a Sim bladder fail while on a date.',
    points: '10',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: '‘Til Death Do Us Part',
    description: 'Have a Sim die at their own wedding.',
    points: '100',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'I’ll get around to it!',
    description: 'Have 10 broken objects on Sim’s lot',
    points: '10',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'Problem Child',
    description: 'Have a Sim reach Level 10 Mischief skill as a teenager.',
    points: '25',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'What Makes a Sim Turn Neutral?',
    description:
      'Have a Sim stay in the Fine emotion for 48 straight Sim hours.',
    points: '25',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'Death of a Salesman',
    description: 'Have a Sim die while running a store',
    points: '25',
    pack: 'Get To Work',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'You-Reek-A',
    description: 'Make a scientific breakthrough while taking a shower',
    points: '10',
    pack: 'Get To Work',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'Autopsy-Turvy',
    description: 'Perform surgery successfully on an Alien',
    points: '10',
    pack: 'Get To Work',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'No Longer Solitary',
    description: 'Bring a hermit back to society.',
    points: '25',
    pack: 'Outdoor Retreat',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'Aspirational',
    description: 'Complete every Aspiration in The Sims 4.',
    points: '100',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: 'Baby Boom',
    description: 'Have 400 babies across all your Sims.',
    points: '50',
    pack: 'Hidden Base Game',
    category: 'Hidden',
    enabled: true,
  },
  {
    name: '9 to 5 to 9',
    description: 'Have a single Sim maintain 3 careers.',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'At Your Service',
    description: 'Hire all services with a single Sim',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Can Reproduce',
    description: 'Have ten babies with a single Sim.',
    points: '0',
    pack: 'Removed',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Flower Power',
    description: 'Have a garden of 10 max quality plants in The Sims 4.',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Horticulture Shock',
    description: 'Collect every Gardening collectible in The Sims 4.',
    points: '0',
    pack: 'Removed',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Jet-Setter',
    description: 'Travel 250 times',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'KamaSimtra',
    description: 'Have a single Sim WooHoo in every possible object.',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Old Lace',
    description: 'Cause 10 NPC deaths on your home lot in The Sims 4.',
    points: '0',
    pack: 'Removed',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Panhandler',
    description:
      'Have a Sim with zero Simoleons to his or her name work for tips.',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Special Guest',
    description: 'Attend 100 Bronze or better Social Events',
    points: '0',
    pack: 'Inactive Base Game',
    category: 'Inactive or Removed',
    enabled: true,
  },
  {
    name: 'Knock, Knock...',
    description: 'Visit 25 different Lots in The Sims 4.',
    points: '50',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Simstagram Celebrity',
    description: 'Gain 1500 Simstagram Followers',
    points: '50',
    pack: 'Cats & Dogs',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Just Getting Started',
    description: 'Play The Sims 4 for 5 hours.',
    points: '25',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Simstagram Influencer',
    description: 'Gain 250 Simstagram Followers',
    points: '25',
    pack: 'Cats & Dogs',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Simstagram Starter',
    description: 'Gain 25 Simstagram Followers',
    points: '25',
    pack: 'Cats & Dogs',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Event Horizon',
    description: 'Earn a Silver rating on 5 different social events.',
    points: '25',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Full House',
    description: 'Play with an eight-Sim household in The Sims 4.',
    points: '10',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Ghostly',
    description: 'Have a Ghost in your household.',
    points: '25',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'The Main Event',
    description: 'Earn a Gold rating on 5 different social events.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Aliens Among Us',
    description: 'Discover 10 Aliens in Disguise',
    points: '50',
    pack: 'Get To Work',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Carried Away',
    description: 'Have Sims be abducted by Aliens 3 times',
    points: '50',
    pack: 'Get To Work',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Ghost Family',
    description: 'Have a family of 8 playable Ghosts.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Vengeful Deity',
    description: 'Kill off 10 of your Sims via unnatural causes.',
    points: '25',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Alphabet Legacy',
    description: 'Play a household for 26 generations or more.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Honorary SimGuru',
    description: 'Play the Sims 4 for 100 hours.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Host with the Most',
    description: 'Host 50 Bronze or better Social Events across all Sims.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'In the Game',
    description: 'Play The Sims 4 for 24 hours.',
    points: '50',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Legacy Leader',
    description:
      'Have 10 households in the world that have been played for ten generations or more.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Legacy Player',
    description: 'Play a household for ten generations or more.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Legendary Legacy',
    description: 'Play a household for 100 generations or more.',
    points: '100',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Whimsical',
    description: 'Complete 100 Whims across all Sims.',
    points: '50',
    pack: 'Base Game',
    category: 'Player Feats',
    enabled: true,
  },
  {
    name: 'Speed Dating',
    description:
      'Have a Sim “first kiss” three times at a single social event.',
    points: '25',
    pack: 'Base Game',
    category: 'Relationships',
    enabled: true,
  },
  {
    name: 'Hello, Darkness, My Old Chum',
    description: 'Have a Sim befriend the Grim Reaper.',
    points: '25',
    pack: 'Base Game',
    category: 'Relationships',
    enabled: true,
  },
  {
    name: '50-Mile-High Club',
    description: 'Successfully WooHoo in a Rocketship.',
    points: '10',
    pack: 'Base Game',
    category: 'Relationships',
    enabled: true,
  },
  {
    name: 'Serial Monogamist',
    description: 'Perform Marriages in 20 Unique Households.',
    points: '50',
    pack: 'Base Game',
    category: 'Relationships',
    enabled: true,
  },
  {
    name: 'Super Best Friends',
    description: 'Make 20 BFFs with Non-Player Sims.',
    points: '50',
    pack: 'Base Game',
    category: 'Relationships',
    enabled: true,
  },
  {
    name: 'Woohoo!',
    description: 'WooHoo with 50 Unique Non-Player Sims.',
    points: '50',
    pack: 'Base Game',
    category: 'Relationships',
    enabled: true,
  },
  {
    name: 'All Nighter',
    description: 'Have a Sim stay awake for 24 straight Sim hours.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Channel Surfer',
    description:
      'Have a Sim listen to all radio stations and watch all TV channels.',
    points: '10',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: "My, You've Changed!",
    description: 'Have a Sim become both max thin and fat within a lifetime.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'On a Whim',
    description: 'Have a Sim complete 10 Whims at a single social event.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Introvert',
    description: 'Have a Sim do nothing social for 24 Sim hours.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Old & Wiser',
    description: 'Have a Sim age up.',
    points: '10',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Basketcase',
    description:
      'Have a Sim get in and out of all primary emotional states within 24 Sim hours.',
    points: '100',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'What would it be like?',
    description: 'WooHoo with a ghost.',
    points: '10',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Black Widow',
    description: 'Have a Sim outlive five spouses.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Double Life',
    description:
      'Have an Alien in disguise marry a Sim without them knowing their secret',
    points: '50',
    pack: 'Get To Work',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Over-Achiever',
    description: 'Have a Sim complete 5 Aspirations.',
    points: '100',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Triple Play',
    description: 'Have a Sim give birth to triplets.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Very Special Delivery',
    description: 'Have a male Sim give birth to an Alien baby',
    points: '50',
    pack: 'Get To Work',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Perfect Llama',
    description:
      'Have a Sim bowl a perfect 10 frame game of all strikes on the bowling lane.',
    points: '125',
    pack: 'Bowling',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Tastes Like Burning',
    description: 'Have a Sim consume every type of toxic plant.',
    points: '25',
    pack: 'Outdoor Retreat',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'The Circle of Life',
    description: 'Play a Sim from birth to natural death.',
    points: '25',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'The Most Interesting Sim in the World',
    description: 'Have a Sim with 12 or more Traits.',
    points: '50',
    pack: 'Base Game',
    category: 'Sim Feats',
    enabled: true,
  },
  {
    name: 'Beyond Repairs',
    description: 'Have a Sim reach max level in the Handiness skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Bow-dacious',
    description: 'Have a Sim reach max level in the Violin skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Cast Away',
    description: 'Have a Sim reach max level in the Fishing skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Code Monk',
    description: 'Have a Sim reach max level in the Programming skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Connoisseurus Rex',
    description: 'Have a Sim reach max level in the Gourmet Cooking skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Elementary',
    description: 'Have a Sim reach max level in the Logic skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Fired Up',
    description: 'Have a Sim reach max level in the Fitness skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Games Within Games',
    description: 'Have a Sim reach max level in the Video Gaming skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Green Thumb',
    description: 'Have a Sim reach max level in the Gardening skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: "It's Not Brain Surgery",
    description: 'Have a Sim reach max level in the Rocket Science Skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Ivory Tower',
    description: 'Have a Sim reach max level in the Piano skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Literal Genius',
    description: 'Have a Sim reach max level in the Writing skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Mael-strum',
    description: 'Have a Sim reach max level in the Guitar skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Mischief Mastered',
    description: 'Have a Sim reach max level in the Mischief skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: "Nature's Course",
    description: 'Have a Sim reach the maximum level in the Herbalism skill.',
    points: '50',
    pack: 'Outdoor Retreat',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Picture Perfect',
    description: 'Have a Sim reach max level in the Photography Skill',
    points: '50',
    pack: 'Get To Work',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Piece of Cake!',
    description: 'Have a Sim reach max level in the Baking Skill',
    points: '50',
    pack: 'Get To Work',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Refined Palette',
    description: 'Have a Sim reach max level in the Painting skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Smooth Talker',
    description: 'Have a Sim reach max level in the Charisma skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Splice of Life',
    description: 'Unlock a new plant type through grafting.',
    points: '25',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Straight for the Jocular',
    description: 'Have a Sim reach max level in the Comedy skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Tender Loving',
    description: 'Have a Sim reach max level in the Mixology Skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Tungsten Chef',
    description: 'Have a Sim reach max level in the Cooking skill.',
    points: '50',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: "I'm the Mix Master",
    description: 'Mix 100 Drinks.',
    points: '25',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'View to a Skill',
    description: 'Reach max level in every skill in The Sims 4.',
    points: '100',
    pack: 'Base Game',
    category: 'Skills & Crafting',
    enabled: true,
  },
  {
    name: 'Critter Catcher',
    description:
      'Collect all the insects and all the new fish in Granite Falls.',
    points: '50',
    pack: 'Outdoor Retreat',
    category: 'Wealth & Collecting',
    enabled: true,
  },
  {
    name: 'For the Hoard!',
    description: 'Complete all collections.',
    points: '100',
    pack: 'Base Game',
    category: 'Wealth & Collecting',
    enabled: true,
  },
  {
    name: 'Harvested Interest',
    description: 'Harvest from 50 wild plants in The Sims 4.',
    points: '25',
    pack: 'Base Game',
    category: 'Wealth & Collecting',
    enabled: true,
  },
  {
    name: 'Rosebud',
    description: 'Gain 1,000,000 Simoleons in a single Household.',
    points: '100',
    pack: 'Base Game',
    category: 'Wealth & Collecting',
    enabled: true,
  },
];
